// Wire Protocol Manifest
//
// Generated by scripts/gen-wire-manifest.mts — do not edit by hand.
// Regenerate with: pnpm --filter @moonshot-ai/agent-core-v2 gen:wire-manifest
//
// protocol_version: "1.5" (migrations: 1.0 -> 1.1 -> 1.2 -> 1.3 -> 1.4 -> 1.5)
//
// One declaration per durable record type — an Event2 subclass declaring
// `static type` + `static durable = true` + `static schema` — drained from the
// runtime EVENT2_REGISTRY ("import = register"). Every payload declaration
// carries its record type in a `_name` field. Payload sketches use TypeScript
// type syntax; when a named type is expanded inline, its name appears as a doc
// comment (`/** ContextMessage */`). Bare type names (ContentPart,
// ContextMessage, …) refer to the real types in src/ — they are intentionally
// not resolved here. `// …` marks a capped field list. On disk (wire.jsonl)
// the journal opens with a metadata line {"type": "metadata",
// "protocol_version", "created_at"}; each record is {"type", ...payload,
// "time"} — object payloads spread at the top level.
//
// Every listed type is durable by construction — transient Event2 classes
// never enter EVENT2_REGISTRY, so there is no persisted flag. Declaration
// header lines: states (every state folding this record type on dispatch and
// replay; any state beyond the first is what the retired format listed as
// cross-reducers), blobs (the folding states whose blob codec offloads inline
// media to blob storage), owner (the source file declaring the class).

// Index (55 record types)
//   config.update                      profile                                         src/agent/profile/profileOps.ts
//   context.append_loop_event          contextMemory, turn                             src/agent/contextMemory/contextEvents.ts
//   context.append_message             contextMemory, plan, task.notificationDelivery  src/agent/contextMemory/contextEvents.ts
//   context.apply_compaction           contextMemory, plan, task.notificationDelivery  src/agent/contextMemory/contextEvents.ts
//   context.clear                      contextMemory, plan, task.notificationDelivery  src/agent/contextMemory/contextEvents.ts
//   context.undo                       contextMemory, plan, task.notificationDelivery  src/agent/contextMemory/contextEvents.ts
//   cron.add                           (none)                                          src/features/cron/cronOps.ts
//   cron.cursor                        (none)                                          src/features/cron/cronOps.ts
//   cron.delete                        (none)                                          src/features/cron/cronOps.ts
//   forked                             (none)                                          src/features/goal/goalOps.ts
//   full_compaction.begin              fullCompaction                                  src/agent/fullCompaction/compactionOps.ts
//   full_compaction.cancel             fullCompaction                                  src/agent/fullCompaction/compactionOps.ts
//   full_compaction.complete           fullCompaction                                  src/agent/fullCompaction/compactionOps.ts
//   goal.clear                         (none)                                          src/features/goal/goalOps.ts
//   goal.create                        (none)                                          src/features/goal/goalOps.ts
//   goal.update                        (none)                                          src/features/goal/goalOps.ts
//   interaction.request                (none)                                          src/features/interaction/interactionOps.ts
//   interaction.resolved               (none)                                          src/features/interaction/interactionOps.ts
//   interruptionReminder.recorded      interruptionReminder                            src/agent/interruptionReminder/interruptionReminderOps.ts
//   llm.request                        llm.requestTrace                                src/agent/llmRequester/llmRequestOps.ts
//   llm.tools_snapshot                 llm.requestTrace                                src/agent/llmRequester/llmRequestOps.ts
//   mcp.tools_discovered               mcp.discovery                                   src/agent/mcp/mcpDiscoveryOps.ts
//   permission.record_approval_result  permissionRules                                 src/agent/permissionRules/permissionRulesOps.ts
//   permission.set_mode                permissionMode, permissionMode.configured       src/agent/permissionMode/permissionModeOps.ts
//   plan_mode.cancel                   plan                                            src/features/plan/planOps.ts
//   plan_mode.enter                    plan                                            src/features/plan/planOps.ts
//   plan_mode.exit                     plan                                            src/features/plan/planOps.ts
//   plan.revision                      plan                                            src/features/plan/planOps.ts
//   plugin.session_start               pluginSessionStartSnapshot                      src/agent/plugin/agentPluginOps.ts
//   profile.bind                       profile, profile.activeTools                    src/agent/profile/profileOps.ts
//   prompt.accepted                    promptAdmission                                 src/agent/prompt/promptOps.ts
//   runtime.set_binding                runtimeBinding                                  src/agent/runtimeBinding/runtimeBindingOps.ts
//   staleGuard.cleared                 staleGuard                                      src/features/staleGuard/staleGuardOps.ts
//   staleGuard.recorded                staleGuard                                      src/features/staleGuard/staleGuardOps.ts
//   swarm_mode.enter                   swarm                                           src/features/swarm/swarmOps.ts
//   swarm_mode.exit                    contextMemory, swarm                            src/features/swarm/swarmOps.ts
//   task.started                       task                                            src/agent/task/taskOps.ts
//   task.terminated                    task                                            src/agent/task/taskOps.ts
//   task.waitDelivered                 task.notificationDelivery                       src/agent/task/taskOps.ts
//   token_counting.measured            (none)                                          src/agent/tokenCounting/tokenCountingOps.ts
//   token_counting.rebased             (none)                                          src/agent/tokenCounting/tokenCountingOps.ts
//   token_counting.truncated           (none)                                          src/agent/tokenCounting/tokenCountingOps.ts
//   token_counting.turn_recorded       (none)                                          src/agent/tokenCounting/tokenCountingOps.ts
//   tools.register_user_tool           userTool                                        src/agent/userTool/userToolOps.ts
//   tools.reset_active_tools           profile.activeTools                             src/agent/profile/profileOps.ts
//   tools.set_active_tools             profile.activeTools                             src/agent/profile/profileOps.ts
//   tools.unregister_user_tool         userTool                                        src/agent/userTool/userToolOps.ts
//   tools.update_store                 (none)                                          src/features/todo/todoOps.ts
//   tower_mode.enter                   tower, tower.owner                              src/features/tower/towerOps.ts
//   tower_mode.exit                    tower, tower.owner                              src/features/tower/towerOps.ts
//   turn.cancel                        turn                                            src/agent/loop/turnOps.ts
//   turn.ended                         turn                                            src/agent/loop/turnOps.ts
//   turn.prompt                        turn                                            src/agent/loop/turnOps.ts
//   turn.steer                         turn                                            src/agent/loop/turnOps.ts
//   usage.record                       (none)                                          src/agent/usage/usageOps.ts

/**
 * states: profile
 * owner: src/agent/profile/profileOps.ts
 */
interface ConfigUpdatePayload {
  _name: 'config.update';
  agentId: string;
  modelAlias?: string;
  profileName?: string;
  /** ThinkingEffort */
  thinkingEffort?: 'off' | 'on' | (string & {});
  /** ThinkingEffort */
  thinkingLevel?: 'off' | 'on' | (string & {});
  systemPrompt?: string;
  /** EnvironmentDisclosureSnapshot */
  environmentDisclosure?: {
    cwd: string;
    date: { disclosed: true, value: { localDate: string, timeZone: string } } | { disclosed: false };
  };
  renderGeneration?: number;
  agentsMdPaths?: string[];
  disallowedTools?: string[];
}

/**
 * states: contextMemory, turn · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextAppendLoopEventPayload {
  _name: 'context.append_loop_event';
  agentId: string;
  /** LoopRecordedEvent */
  event: 'step.begin' | 'step.end' | 'content.part' | 'tool.call' | 'tool.result';
}

/**
 * states: contextMemory, plan, task.notificationDelivery · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextAppendMessagePayload {
  _name: 'context.append_message';
  agentId: string;
  /** ContextMessage */
  message: {
    role: 'system' | 'user' | 'assistant' | 'tool';
    name?: string;
    content: ('text' | 'think' | 'image_url' | 'audio_url' | 'video_url')[];
    toolCalls: {
      type: 'function';
      id: string;
      name: string;
      arguments: string | null;
      extras?: Record<string, unknown>;
      _streamIndex?: number | string;
    }[];
    toolCallId?: string;
    partial?: boolean;
    tools?: {
      name: string;
      description: string;
      parameters: Record<string, unknown>;
      deferred?: true;
    }[];
    id?: string;
    providerMessageId?: string;
    origin?: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry' | undefined;
    isError?: boolean;
    note?: string;
  };
}

/**
 * states: contextMemory, plan, task.notificationDelivery · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 * shared base: ...contextCompactionBaseShape
 */
type ContextApplyCompactionPayload = { _name: 'context.apply_compaction'; } & ({ summary: string, compactedCount: number, contextSummary?: string } | { contextSummary: string, compactedCount: number, summary?: string } | { summary: ContextMessage, count: number, compactedCount?: number });

/**
 * states: contextMemory, plan, task.notificationDelivery · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextClearPayload {
  _name: 'context.clear';
  agentId: string;
}

/**
 * states: contextMemory, plan, task.notificationDelivery · blobs: contextMemory
 * owner: src/agent/contextMemory/contextEvents.ts
 */
interface ContextUndoPayload {
  _name: 'context.undo';
  agentId: string;
  count: number;
}

/**
 * states: (none)
 * owner: src/features/cron/cronOps.ts
 */
interface CronAddPayload {
  _name: 'cron.add';
  task: {
    id: string;
    cron: string;
    prompt: string;
    createdAt: number;
    recurring?: boolean;
    lastFiredAt?: number;
    tags?: Record<string, string>;
  };
}

/**
 * states: (none)
 * owner: src/features/cron/cronOps.ts
 */
interface CronCursorPayload {
  _name: 'cron.cursor';
  id: string;
  lastFiredAt: number;
}

/**
 * states: (none)
 * owner: src/features/cron/cronOps.ts
 */
interface CronDeletePayload {
  _name: 'cron.delete';
  ids: string[];
}

/**
 * states: (none)
 * owner: src/features/goal/goalOps.ts
 */
interface ForkedPayload {
  _name: 'forked';
  agentId: string;
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionBeginPayload {
  _name: 'full_compaction.begin';
  agentId: string;
  instruction?: string;
  /** CompactionSource */
  source: 'manual' | 'auto';
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCancelPayload {
  _name: 'full_compaction.cancel';
  agentId: string;
}

/**
 * states: fullCompaction
 * owner: src/agent/fullCompaction/compactionOps.ts
 */
interface FullCompactionCompletePayload {
  _name: 'full_compaction.complete';
  agentId: string;
}

/**
 * states: (none)
 * owner: src/features/goal/goalOps.ts
 */
interface GoalClearPayload {
  _name: 'goal.clear';
  agentId: string;
}

/**
 * states: (none)
 * owner: src/features/goal/goalOps.ts
 */
interface GoalCreatePayload {
  _name: 'goal.create';
  agentId: string;
  goalId: string;
  objective: string;
  completionCriterion?: string;
  wallClockResumedAt?: number;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  actor?: 'user' | 'model' | 'runtime' | 'system';
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
}

/**
 * states: (none)
 * owner: src/features/goal/goalOps.ts
 */
interface GoalUpdatePayload {
  _name: 'goal.update';
  agentId: string;
  goalId?: string;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  reason?: string;
  turnsUsed?: number;
  tokensUsed?: number;
  wallClockMs?: number;
  wallClockResumedAt?: number;
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
  actor?: 'user' | 'model' | 'runtime' | 'system';
}

/**
 * states: (none)
 * owner: src/features/interaction/interactionOps.ts
 */
interface InteractionRequestPayload {
  _name: 'interaction.request';
  agentId: string;
  id: string;
  kind: 'approval' | 'question' | 'user_tool';
  toolCallId?: string;
  request: any;
}

/**
 * states: (none)
 * owner: src/features/interaction/interactionOps.ts
 */
interface InteractionResolvedPayload {
  _name: 'interaction.resolved';
  agentId: string;
  id: string;
  response: any;
}

/**
 * states: interruptionReminder
 * owner: src/agent/interruptionReminder/interruptionReminderOps.ts
 */
interface InterruptionReminderRecordedPayload {
  _name: 'interruptionReminder.recorded';
  agentId: string;
  turnId: number;
}

/**
 * states: llm.requestTrace
 * owner: src/agent/llmRequester/llmRequestOps.ts
 */
interface LlmRequestPayload {
  _name: 'llm.request';
  agentId: string;
  kind: 'loop' | 'compaction';
  provider: string;
  model: string;
  modelAlias?: string;
  /** ThinkingEffort */
  thinkingEffort?: 'off' | 'on' | (string & {});
  thinkingKeep?: string;
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  betaApi?: boolean;
  toolSelect: boolean;
  systemPromptHash: string;
  systemPrompt?: string;
  toolsHash: string;
  messageCount: number;
  turnStep?: string;
  attempt?: string;
  projection?: 'strict' | 'media-degraded' | 'media-stripped' | 'strict-media-degraded' | 'strict-media-stripped';
  droppedCount?: number;
}

/**
 * states: llm.requestTrace
 * owner: src/agent/llmRequester/llmRequestOps.ts
 */
interface LlmToolsSnapshotPayload {
  _name: 'llm.tools_snapshot';
  agentId: string;
  hash: string;
  tools: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  }[];
}

/**
 * states: mcp.discovery
 * owner: src/agent/mcp/mcpDiscoveryOps.ts
 */
interface McpToolsDiscoveredPayload {
  _name: 'mcp.tools_discovered';
  agentId: string;
  serverName: string;
  hash: string;
  tools: readonly MCPToolDefinition[];
  enabledNames: string[];
  collisions?: {
    qualified: string;
    toolName: string;
    collidesWith: { kind: 'same_server', toolName: string } | { kind: 'other_server', serverName: string };
  }[];
}

/**
 * states: permissionRules
 * owner: src/agent/permissionRules/permissionRulesOps.ts
 */
interface PermissionRecordApprovalResultPayload {
  _name: 'permission.record_approval_result';
  agentId: string;
  turnId: number;
  toolCallId: string;
  toolName: string;
  action: string;
  sessionApprovalRule?: string;
  result: PermissionApprovalResultRecord['result'];
}

/**
 * states: permissionMode, permissionMode.configured
 * owner: src/agent/permissionMode/permissionModeOps.ts
 */
interface PermissionSetModePayload {
  _name: 'permission.set_mode';
  agentId: string;
  /** PermissionMode */
  mode: 'manual' | 'yolo' | 'auto';
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeCancelPayload {
  _name: 'plan_mode.cancel';
  agentId: string;
  id?: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeEnterPayload {
  _name: 'plan_mode.enter';
  agentId: string;
  id: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanModeExitPayload {
  _name: 'plan_mode.exit';
  agentId: string;
  id?: string;
}

/**
 * states: plan
 * owner: src/features/plan/planOps.ts
 */
interface PlanRevisionPayload {
  _name: 'plan.revision';
  agentId: string;
  id: string;
  version: number;
  path: string;
  sha256: string;
  bytes: number;
}

/**
 * states: pluginSessionStartSnapshot
 * owner: src/agent/plugin/agentPluginOps.ts
 */
interface PluginSessionStartPayload {
  _name: 'plugin.session_start';
  agentId: string;
  content: string | null;
}

/**
 * states: profile, profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ProfileBindPayload {
  _name: 'profile.bind';
  agentId: string;
  modelAlias?: string;
  profileName?: string;
  /** ThinkingEffort */
  thinkingEffort: 'off' | 'on' | (string & {});
  systemPrompt: string;
  /** EnvironmentDisclosureSnapshot */
  environmentDisclosure?: {
    cwd: string;
    date: { disclosed: true, value: { localDate: string, timeZone: string } } | { disclosed: false };
  };
  renderGeneration?: number;
  agentsMdPaths?: string[];
  activeToolNames?: string[];
  disallowedTools: string[];
  subagents?: string[];
}

/**
 * states: promptAdmission
 * owner: src/agent/prompt/promptOps.ts
 */
interface PromptAcceptedPayload {
  _name: 'prompt.accepted';
  agentId: string;
  promptId: string;
  content?: any;
}

/**
 * states: runtimeBinding
 * owner: src/agent/runtimeBinding/runtimeBindingOps.ts
 */
interface RuntimeSetBindingPayload {
  _name: 'runtime.set_binding';
  agentId: string;
  workspaceId: string;
  runtimeId: string;
}

/**
 * states: staleGuard
 * owner: src/features/staleGuard/staleGuardOps.ts
 */
interface StaleGuardClearedPayload {
  _name: 'staleGuard.cleared';
}

/**
 * states: staleGuard
 * owner: src/features/staleGuard/staleGuardOps.ts
 */
interface StaleGuardRecordedPayload {
  _name: 'staleGuard.recorded';
  path: string;
  mtimeMs: number;
}

/**
 * states: swarm
 * owner: src/features/swarm/swarmOps.ts
 */
interface SwarmModeEnterPayload {
  _name: 'swarm_mode.enter';
  agentId: string;
  /** SwarmModeTrigger */
  trigger: 'manual' | 'task' | 'tool';
}

/**
 * states: contextMemory, swarm · blobs: contextMemory
 * owner: src/features/swarm/swarmOps.ts
 */
interface SwarmModeExitPayload {
  _name: 'swarm_mode.exit';
  agentId: string;
}

/**
 * states: task
 * owner: src/agent/task/taskOps.ts
 */
interface TaskStartedPayload {
  _name: 'task.started';
  agentId: string;
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
}

/**
 * states: task
 * owner: src/agent/task/taskOps.ts
 */
interface TaskTerminatedPayload {
  _name: 'task.terminated';
  agentId: string;
  /** AgentTaskInfo */
  info: AgentTaskInfoByKind[AgentTaskKind];
  outputTail?: string;
}

/**
 * states: task.notificationDelivery
 * owner: src/agent/task/taskOps.ts
 */
interface TaskWaitDeliveredPayload {
  _name: 'task.waitDelivered';
  agentId: string;
  keys: string[];
}

/**
 * states: (none)
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingMeasuredPayload {
  _name: 'token_counting.measured';
  agentId: string;
  length: number;
  tokens: number;
}

/**
 * states: (none)
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingRebasedPayload {
  _name: 'token_counting.rebased';
  agentId: string;
  length: number;
  tokens: number;
  measured: boolean;
}

/**
 * states: (none)
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingTruncatedPayload {
  _name: 'token_counting.truncated';
  agentId: string;
  length: number;
  tokens: number;
}

/**
 * states: (none)
 * owner: src/agent/tokenCounting/tokenCountingOps.ts
 */
interface TokenCountingTurnRecordedPayload {
  _name: 'token_counting.turn_recorded';
  agentId: string;
  length: number;
  tokens: number;
  turnId: number;
}

/**
 * states: userTool
 * owner: src/agent/userTool/userToolOps.ts
 */
interface ToolsRegisterUserToolPayload {
  _name: 'tools.register_user_tool';
  agentId: string;
  name: string;
  description: string;
  parameters: UserToolRegistration['parameters'];
  disclosure?: UserToolRegistration['disclosure'];
}

/**
 * states: profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ToolsResetActiveToolsPayload {
  _name: 'tools.reset_active_tools';
  agentId: string;
}

/**
 * states: profile.activeTools
 * owner: src/agent/profile/profileOps.ts
 */
interface ToolsSetActiveToolsPayload {
  _name: 'tools.set_active_tools';
  agentId: string;
  names: string[];
}

/**
 * states: userTool
 * owner: src/agent/userTool/userToolOps.ts
 */
interface ToolsUnregisterUserToolPayload {
  _name: 'tools.unregister_user_tool';
  agentId: string;
  name: string;
}

/**
 * states: (none)
 * owner: src/features/todo/todoOps.ts
 */
interface ToolsUpdateStorePayload {
  _name: 'tools.update_store';
  agentId: string;
  key: string;
  value: any;
}

/**
 * states: tower, tower.owner
 * owner: src/features/tower/towerOps.ts
 */
interface TowerModeEnterPayload {
  _name: 'tower_mode.enter';
  agentId: string;
  sessionId?: string;
}

/**
 * states: tower, tower.owner
 * owner: src/features/tower/towerOps.ts
 */
interface TowerModeExitPayload {
  _name: 'tower_mode.exit';
  agentId: string;
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnCancelPayload {
  _name: 'turn.cancel';
  agentId: string;
  turnId?: number;
  target?: 'active' | 'queued';
  reason?: 'user_cancelled' | 'aborted';
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnEndedPayload {
  _name: 'turn.ended';
  agentId: string;
  turnId: number;
  reason: 'completed' | 'cancelled' | 'failed' | 'blocked';
  /** KimiErrorPayload */
  error?: {
    code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
    message: string;
    name?: string;
    details?: Readonly<Record<string, unknown>>;
    retryable: boolean;
    cause?: {
      code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
      message: string;
      name?: string;
      details?: Readonly<Record<string, unknown>>;
      retryable: boolean;
      cause?: {
        code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
        message: string;
        name?: string;
        details?: Readonly<Record<string, unknown>>;
        retryable: boolean;
        cause?: {
          code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
          message: string;
          name?: string;
          details?: Readonly<Record<string, unknown>>;
          retryable: boolean;
          cause?: {
            code: (typeof ErrorCodes)[keyof typeof ErrorCodes];
            message: string;
            name?: string;
            details?: Readonly<Record<string, unknown>>;
            retryable: boolean;
            cause?: {
              code: ErrorCode;
              message: string;
              name?: string;
              details?: Readonly<Record<string, unknown>>;
              retryable: boolean;
              cause?: ErrorPayload;
            };
          };
        };
      };
    };
  };
  durationMs?: number;
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnPromptPayload {
  _name: 'turn.prompt';
  agentId: string;
  input: readonly ContentPart[];
  /** PromptOrigin */
  origin: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry';
}

/**
 * states: turn
 * owner: src/agent/loop/turnOps.ts
 */
interface TurnSteerPayload {
  _name: 'turn.steer';
  agentId: string;
  input: readonly ContentPart[];
  /** PromptOrigin */
  origin: 'user' | 'skill_activation' | 'plugin_command' | 'injection' | 'shell_command' | 'compaction_summary' | 'system_trigger' | 'task' | 'cron_job' | 'cron_missed' | 'hook_result' | 'retry';
}

/**
 * states: (none)
 * owner: src/agent/usage/usageOps.ts
 */
interface UsageRecordPayload {
  _name: 'usage.record';
  agentId: string;
  model: string;
  /** TokenUsage */
  usage: {
    inputOther: number;
    output: number;
    inputCacheRead: number;
    inputCacheCreation: number;
  };
  /** UsageRecordScope */
  usageScope?: 'session' | 'turn';
}

/** Record type → payload sketch. */
interface WirePayloadMap {
  "config.update": ConfigUpdatePayload;
  "context.append_loop_event": ContextAppendLoopEventPayload;
  "context.append_message": ContextAppendMessagePayload;
  "context.apply_compaction": ContextApplyCompactionPayload;
  "context.clear": ContextClearPayload;
  "context.undo": ContextUndoPayload;
  "cron.add": CronAddPayload;
  "cron.cursor": CronCursorPayload;
  "cron.delete": CronDeletePayload;
  "forked": ForkedPayload;
  "full_compaction.begin": FullCompactionBeginPayload;
  "full_compaction.cancel": FullCompactionCancelPayload;
  "full_compaction.complete": FullCompactionCompletePayload;
  "goal.clear": GoalClearPayload;
  "goal.create": GoalCreatePayload;
  "goal.update": GoalUpdatePayload;
  "interaction.request": InteractionRequestPayload;
  "interaction.resolved": InteractionResolvedPayload;
  "interruptionReminder.recorded": InterruptionReminderRecordedPayload;
  "llm.request": LlmRequestPayload;
  "llm.tools_snapshot": LlmToolsSnapshotPayload;
  "mcp.tools_discovered": McpToolsDiscoveredPayload;
  "permission.record_approval_result": PermissionRecordApprovalResultPayload;
  "permission.set_mode": PermissionSetModePayload;
  "plan_mode.cancel": PlanModeCancelPayload;
  "plan_mode.enter": PlanModeEnterPayload;
  "plan_mode.exit": PlanModeExitPayload;
  "plan.revision": PlanRevisionPayload;
  "plugin.session_start": PluginSessionStartPayload;
  "profile.bind": ProfileBindPayload;
  "prompt.accepted": PromptAcceptedPayload;
  "runtime.set_binding": RuntimeSetBindingPayload;
  "staleGuard.cleared": StaleGuardClearedPayload;
  "staleGuard.recorded": StaleGuardRecordedPayload;
  "swarm_mode.enter": SwarmModeEnterPayload;
  "swarm_mode.exit": SwarmModeExitPayload;
  "task.started": TaskStartedPayload;
  "task.terminated": TaskTerminatedPayload;
  "task.waitDelivered": TaskWaitDeliveredPayload;
  "token_counting.measured": TokenCountingMeasuredPayload;
  "token_counting.rebased": TokenCountingRebasedPayload;
  "token_counting.truncated": TokenCountingTruncatedPayload;
  "token_counting.turn_recorded": TokenCountingTurnRecordedPayload;
  "tools.register_user_tool": ToolsRegisterUserToolPayload;
  "tools.reset_active_tools": ToolsResetActiveToolsPayload;
  "tools.set_active_tools": ToolsSetActiveToolsPayload;
  "tools.unregister_user_tool": ToolsUnregisterUserToolPayload;
  "tools.update_store": ToolsUpdateStorePayload;
  "tower_mode.enter": TowerModeEnterPayload;
  "tower_mode.exit": TowerModeExitPayload;
  "turn.cancel": TurnCancelPayload;
  "turn.ended": TurnEndedPayload;
  "turn.prompt": TurnPromptPayload;
  "turn.steer": TurnSteerPayload;
  "usage.record": UsageRecordPayload;
}
